CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_number VARCHAR(255) NOT NULL UNIQUE,
    first_name VARCHAR(255) NOT NULL,
    middle_name VARCHAR(255),
    family_name VARCHAR(255) NOT NULL,
    name_extension VARCHAR(255),
    birthdate DATE NOT NULL,
    age INT NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    auth_question_1 VARCHAR(255) NOT NULL,
    auth_answer_1 VARCHAR(255) NOT NULL,
    auth_question_2 VARCHAR(255) NOT NULL,
    auth_answer_2 VARCHAR(255) NOT NULL,
    auth_question_3 VARCHAR(255) NOT NULL,
    auth_answer_3 VARCHAR(255) NOT NULL,
    purok_street VARCHAR(255) NOT NULL,
    barangay VARCHAR(255) NOT NULL,
    municipal_city VARCHAR(255) NOT NULL,
    province VARCHAR(255) NOT NULL,
    country VARCHAR(255) NOT NULL,
    zip_code VARCHAR(255) NOT NULL
);